# Temperature paramter effects the influence the weight has
# on control updates. A small lambda will focus the update more towards
# the best controls for that iteration.
# A larger lambda will be more forgiving to sub-optimal perturbations.
lambda: 0.01
# sampling variance left wheel velocity
ul_var: 0.9
# sampling variance right wheel velocity
ur_var: 0.9
# time horizon (s)
horizon: 1.0
# time step (s)
time_step: 0.01
# number of rollouts
rollouts: 5
# initial controls
# left wheel
ul_init: 0.0
# right wheel
ur_init: 0.0
# loss parameters represent diagnols of matrix
# penalize on states
Q: [10000.0, 10000.0, 1.0]
# penalize controls
R: [0.1, 0.1]
# penalize terminal states
P1: [1000.0, 1000.0, 1000.0]
