# The width of the wheels
wheel_width: 0.2
# The radius of the wheels
wheel_radius: 0.35
#  The distance between the centers wheels
wheel_base: 1
# The length of the main chassis link
chassis_length: 1
# The thickness of the plate that forms the chassis
chassis_thickness: 0.5
